bd.user=n1;
bd.password=n2;
bd.connectLine=c1
jiraApi.user=u1
jiraApi.password=u2
jiraApi.projectId=28106
jiraApi.maxResults=4000
jiraApi.TestCaseStatus=/rest/tests/1.0/project/28106/testcasestatus
jiraApi.FolderTreeUrl=/rest/tests/1.0/project/28106/foldertree/testcase
jiraApi.CustomFieldsUrl=/rest/tests/1.0/project/28106/customfields/testcase
jiraApi.TestCasesUrl=/rest/tests/1.0/testcase/search?archived=false&fields=id,key,projectId,name,averageTime,estimatedTime,labels,folderId,componentId,statusId,priorityId,lastTestResultStatus(name,i18nKey,color),majorVersion,createdOn,createdBy,updatedOn,updatedBy,customFieldValues,owner&maxResults=0000&query=testCase.projectId+IN+(00000)+AND+testCase.folderTreeId+IN+(60115)+ORDER+BY+testCase.ownerKey+DESC&sort=owner:desc&startAt=0
max.workers=10