bd.user=n1;
bd.password=n2;
bd.connectLine=c1
jiraApi.user=u1
jiraApi.password=u2
jiraApi.projectId=28106
jiraApi.maxResults=4000
jiraApi.AuthorizationUrl=t1
jiraApi.FolderTreeUrl=t2
jiraApi.CustomFieldsUrl=t3
jiraApi.TestCasesUrl=t4
max.workers=10