bd.user=n1;
bd.password=n2;
jira.user=n3;
jira.password=n4;
jiraApi.AuthorizathionUrl=http://test.ru
jiraApi.FolderTreeUrl=http://test.ru
jiraApi.ConfigUrl=http://test.ru
jiraApi.TestcasesUrl=http://test.ru